apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki_grabber
spec:
  # A cron running at midnight would look like:
  # schedule: "0 0 * * *"
  # Our cron runs every minute instead for debugging
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl 
            - -L 
            - https://en.wikipedia.org/api/rest_v1/page/random/html
          restartPolicy: OnFailure